name: Common Setup
description: Setup Node.js, install dependencies

inputs:
  install-smart-contract-deps:
    description: Install dependencies for libs/blockchain/smart-contract
    required: false
    default: 'false'

runs:
  using: composite
  steps:
    - name: Setup Node.js
      uses: actions/setup-node@v6
      with:
        node-version: 24.13.x
        cache: 'npm'

    - name: Install Dependencies
      shell: bash
      run: npm ci --no-audit --no-fund

    - name: Install Smart Contract Dependencies
      if: ${{ inputs.install-smart-contract-deps == 'true' }}
      shell: bash
      run: npm --prefix libs/blockchain/smart-contract ci --no-audit --no-fund
