/*
 * Copyright Fraunhofer Institute for Material Flow and Logistics
 *
 * Licensed under the Apache License, Version 2.0 (the "License").
 * For details on the licensing terms, see the LICENSE file.
 * SPDX-License-Identifier: Apache-2.0
 */

export enum ErrorCode {
  BLOCKCHAIN_NOT_INITIALIZED = 'BLOCKCHAIN_NOT_INITIALIZED',
  BLOCKCHAIN_RETRIEVE_FAILED = 'BLOCKCHAIN_RETRIEVE_FAILED',
  BLOCKCHAIN_STORE_FAILED = 'BLOCKCHAIN_STORE_FAILED',
  DATABASE_CONSTRAINT = 'DATABASE_CONSTRAINT',
  DATABASE_ERROR = 'DATABASE_ERROR',
  DATABASE_RECORD_CONFLICT = 'DATABASE_RECORD_CONFLICT',
  DATABASE_RECORD_NOT_FOUND = 'DATABASE_RECORD_NOT_FOUND',
  DOMAIN_BUSINESS_RULE_VIOLATION = 'DOMAIN_BUSINESS_RULE_VIOLATION',
  DOMAIN_INCOMPATIBLE_DATA = 'DOMAIN_INCOMPATIBLE_DATA',
  DOMAIN_RESOURCE_INACTIVE = 'DOMAIN_RESOURCE_INACTIVE',
  STORAGE_DOWNLOAD_FAILED = 'STORAGE_DOWNLOAD_FAILED',
  STORAGE_TIMEOUT = 'STORAGE_TIMEOUT',
  STORAGE_UPLOAD_FAILED = 'STORAGE_UPLOAD_FAILED',
  INTERNAL_ERROR = 'INTERNAL_ERROR',
  VALIDATION_ERROR = 'VALIDATION_ERROR',
}
