export enum EnergySource {
  SOLAR_ENERGY = 'SOLAR_ENERGY',
  WIND_ENERGY = 'WIND_ENERGY',
  HYDROPOWER = 'HYDROPOWER',
  BIOMASS = 'BIOMASS',
  NUCLEAR_ENERGY = 'NUCLEAR_ENERGY',
  FOSSIL_FUELS = 'FOSSIL_FUELS',
  MINE_GAS = 'MINE_GAS',
  GEOTHERMAL_ENERGY = 'GEOTHERMAL_ENERGY',
}
