export enum ProcessType {
  POWER_PRODUCTION = 'POWER_PRODUCTION',
  HYDROGEN_PRODUCTION = 'HYDROGEN_PRODUCTION',
  HYDROGEN_BOTTLING = 'HYDROGEN_BOTTLING',
  HYDROGEN_TRANSPORTATION = 'HYDROGEN_TRANSPORTATION',
}
