[[chapter-building-block-view]]
:docinfo: shared
:toc: left
:toclevels: 3
:sectnums:
:copyright: Apache License 2.0

= Building Block View

The building block view is a static and hierarchical decomposition of the system into building blocks and their relationships.
It is a collection descriptions for all important components.
Building blocks may be modules, components, subsystems, classes, interfaces, packages, libraries, frameworks, layers, partitions, tiers, functions, macros, operations, data structures, etc.).

For interface specifications, including all method signatures and their descriptions, we refer to the _OpenAPI_ documents.
Only other kinds of interfaces are described here.
This is a simplification of arc42 (which requires a short description of interfaces), to avoid redundancy and inconsistencies, and to reduce documentation efforts.

== Overview

The H2-Trust project mainly consists of two parts: a frontend and a backend.
The frontend is a web interface for the user and was developed using Angular.
The backend consists of an API gateway, which is responsible for routing requests from the frontend to the corresponding service, and a number of services, which provide the business logic. All three backend applications are implemented using TypeScript and Node.js.
Additionally, the backend utilizes a database, an object storage system, and a blockchain for data storage.

image:images/02-building-block-view/system-architecture.svg[]

== Building Blocks - Level 1

In level 1, the components of H2-Trust are shown.

[cols="1,1,3",options="header"]
|===
| Name
| Status
| Responsibility / Description

| Frontend
| Custom development
| The frontend is the user interface of the project. All actions such as batch creation are carried out from here and all saved data can be viewed.

| API service
| Custom development
| The service that receives the interface calls from the frontend and forwards them to the other services.

| General service
| Custom development
| The general service is responsible for managing master data such as companies and users. This includes the creation, fetching and possible updating of these objects.

| Batch service
| Custom development
| The batch service handles all tasks related to batches. This includes creating new hydrogen batches, creating them on the basis of existing batches and fetching them, including all associated batches.

| Process service
| Custom development
| The process service handles all workflows. This includes creating productions or generating reports.

| Message-broker
| Message-broker software
| The service that connects all services from the API service onwards.

| Postgres database
| Relational database management system
| All information is stored non-temporarily here.

| MinIO File Storage
| Object storage system
| Documents such as certificates are stored here.

| Keycloak
| Single sign-on system
| An authorization service with which user logins are implemented and managed.
|===


== Building Blocks - Level 2

TBD

== Building Blocks - Level 3

TBD