name: Danger

on:
  pull_request:

concurrency:
  group: danger-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  danger:
    runs-on: ubuntu-latest
    timeout-minutes: 5

    permissions:
      contents: read
      pull-requests: write
      statuses: write
      issues: write

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v6

      - name: Common Setup
        uses: ./.github/actions/common-setup

      - name: Run Danger
        run: npx danger ci --failOnErrors
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
