name: Dependabot
on:
  pull_request_target:
    types: [opened, synchronize, reopened]

permissions:
  contents: write
  pull-requests: write

jobs:
  auto-merge-and-approve:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    if: >
      github.actor == 'dependabot[bot]' && github.event.pull_request.user.login == 'dependabot[bot]' &&
      github.event.pull_request.head.repo.fork == false
    steps:
      - name: Fetch Dependabot Metadata
        id: metadata
        uses: dependabot/fetch-metadata@v2
        with:
          github-token: '${{ secrets.GITHUB_TOKEN }}'

      - name: Label Patch Updates
        if: >
          steps.metadata.outputs.update-type == 'version-update:semver-patch'
        run: gh pr edit "$PR_URL" --add-label "patch"
        env:
          PR_URL: ${{ github.event.pull_request.html_url }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Label Minor Updates
        if: >
          steps.metadata.outputs.update-type == 'version-update:semver-minor'
        run: gh pr edit "$PR_URL" --add-label "minor"
        env:
          PR_URL: ${{ github.event.pull_request.html_url }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Label Major Updates
        if: steps.metadata.outputs.update-type == 'version-update:semver-major'
        run: gh pr edit "$PR_URL" --add-label "major"
        env:
          PR_URL: ${{ github.event.pull_request.html_url }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Approve PR for Patch and Minor Updates
        if: >
          steps.metadata.outputs.update-type == 'version-update:semver-patch' || steps.metadata.outputs.update-type ==
          'version-update:semver-minor'
        run: gh pr review --approve "$PR_URL"
        env:
          PR_URL: ${{ github.event.pull_request.html_url }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Auto-Merge Patch and Minor Updates
        if: >
          steps.metadata.outputs.update-type == 'version-update:semver-patch' || steps.metadata.outputs.update-type ==
          'version-update:semver-minor'
        run: gh pr merge --auto --squash "$PR_URL"
        env:
          PR_URL: ${{ github.event.pull_request.html_url }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
