name: Slither

on:
  workflow_dispatch:
  pull_request:
    paths:
      - 'libs/blockchain/smart-contract/**'

jobs:
  analyze:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      security-events: write

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v6

      - name: Run Slither
        id: slither
        uses: crytic/slither-action@v0.4.2
        with:
          node-version: 22 
          target: 'libs/blockchain/smart-contract'
